/*
 * Hello World Demo for gem5 Syscall Emulation
 * 
 * This program demonstrates the most basic syscalls:
 * - write() for output
 * - exit() for termination
 * 
 * Compile: gcc -static -o hello hello.c
 * Run:     gem5.opt run_gem5.py
 */

#include <stdio.h>
#include <unistd.h>

int main() {
    // Using printf - internally calls write(1, buffer, len)
    printf("Hello from gem5 syscall emulation!\n");
    printf("This message is generated by a simulated x86-64 CPU.\n");
    
    // Demonstrate direct write syscall
    const char *msg = "\n[Direct syscall] Writing to stdout...\n";
    write(STDOUT_FILENO, msg, 42);
    
    // Write to stderr too
    const char *err_msg = "[stderr] This goes to stderr!\n";
    write(STDERR_FILENO, err_msg, 31);
    
    printf("\nDemo completed successfully!\n");
    
    // Exit with code 0 (success)
    return 0;
}
